#!/usr/bin/env bash
# The port's acceptance test: run the combat-math contract through GDScript.
#
# ⚠️ RE-COPY THE CONTRACTS FIRST IF THE TS MATH CHANGED. They are generated by
# `npx tsx tools/exportport.ts` and diffed against the live TS fixtures on every `npm test`,
# so the TS side cannot go stale — but this project holds a COPY, and that copy can.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
for c in combat derive status tick classify data; do
  cp "$here/../src/tamerengine/$c.json" "$here/data/$c.json"
done
# ⚠️ NAME THE CONTRACT SCENE EXPLICITLY. This line used to rely on the project's `run/main_scene`
# being the contract — which silently stopped being true the moment the playable game got a title
# screen. `--headless --path .` then booted the GAME, printed no test output, and hung until the
# caller's timeout killed it: an acceptance test that could never fail because it never ran.
"${GODOT:-P:/Godot_v4.7.1-stable_win64.exe}" --headless --path "$here" res://scenes/contract_test.tscn
