// In-game short bios for ALL 65 species (full versions + per-body-family themes in
// docs/BESTIARY.md). Kept condensed; the long-form doc is the canonical lore.
//
// ⚠️ REWRITTEN 2026-08-07 FOR THE APPEARANCE-FIRST IDENTITIES. Every species was renamed from
// the creature actually on screen (species.ts carries the new names; ids are stable). The seven
// narrative arcs — displacement, the scattering, the itinerant fair, the deep stirring, the
// fading nests, the long wait, the Lab's first-age fusions — are WORLD lore and survived the
// recast; the creatures living inside them are new. Innate names referenced here are the live
// ones from species.ts — if an innate is renamed there, rename it here.
export const BIOS: Record<string, string> = {
  // --- Mammal: displacement & renewed purpose ---
  kongrath: 'Gruulk grew up the biggest, quietest member of a wandering troupe of smaller, mismatched creatures who banded together for safety on the road. Nothing approached the green-hided colossus twice, and he never asked to be their protector — he was simply the one standing in front. When the troupe finally scattered, he found he missed having something worth standing between, and joined the Circuit looking for it all over again. The first Chest Beat of a match is him announcing he has found it.',
  aegisox: 'Terrock stood a mountain pass for a working lifetime — a squared, quarry-tan wall the caravans planned their routes around. When the caravans traded living guardians for engines, the pass no longer needed a wall, and a wall is all Terrock ever wanted to be. The arena still needs one. She fights to shield her teammates more than to win, and Immovable is not a boast, it is a job description.',
  maneleo: 'Manegold led a company of prize-fighters until a younger rival talked it out from under him, and refusing exile, he walked onto the Circuit to rebuild his name from nothing. The tawny hood of fur falls around his face like a mane and he leads from the front, first into the line, loudest at the Rallying Roar — gathering a new company one teammate at a time.',
  grivvel: 'Grynt\'s scrubland territory shrank a little more every season — hungrier rivals, a road through his old range — until the wild simply left the wiry green scrapper behind. The Circuit is the first place in years with honest, deliberate boundaries, and he treats every one of them as negotiable. He is already picking the next fight before the last one has cooled.',
  ursath: 'Frostmaul woke from a long mountain sleep to find his high forest felled and paved. The blue-white mauler wanders the Circuit half in search of a new home, half for the honest satisfaction of a Maul landing true — and the crowd has learned to love the unhurried way he winds one up.',
  // --- Avian: scarcity, migration, and the long way back ---
  pinguox: 'Capling was born mid-trek, in a generation that never saw the colony her parents fled. Word has finally come back that the old grounds are safe again, and the little teal diver is testing every plunge of the long journey home on the Circuit — Dive Bomb lands a little truer with each attempt, and she is cheerfully unbothered that everything she fights is bigger than she is.',
  strixil: 'Aeristra stayed behind when the scattering emptied her roost, drifting the old thermals alone and keeping its knowledge alive for whoever eventually found their way back. Now the drifters trickle home in twos and threes, and the pale-blue floater has become the archivist they all quietly rely on — Silent Wisdom is not a technique, it is a habit that never broke.',
  balaenix: 'Azurefin was born in backwaters the others abandoned mid-scattering, and stayed rather than follow — the stillness suited her. A deep-blue drifter with pale fins like sails, she hangs motionless until the moment stops being one. Statue Stance for an hour; Ambush Strike once. The crowd never sees it coming, which is the point of the crowd, as far as she is concerned.',
  corvaan: 'Cobalon learned to make a home out of nowhere in particular during the long scattering, picking up trinkets and a stolen spellbook from every territory the wind blew him through. Now that the old roosts call everyone back, the cobalt scholar finds he would rather collect reputation than a nest — every Arcane Bolt is a page of that book, cast at somebody.',
  larkessa: 'Rosewing\'s voice became more than talent during the scattering — flung far enough on the wind, it helped the separated find each other across a continent of empty sky. The roosts are full again, and when the rose-tinted songwing opens a match with the Song of Valor, the applause still reminds her that every one of those voices made it home.',
  // --- Marsupial: the itinerant fair ---
  bruxaroo: 'Mosshorn made his name in staged fairground exhibition bouts and grew tired of the choreography. The green, moss-crowned brawler came to the Circuit hungry for real competition and the honest thud of an unrehearsed Haymaker — and the grin after it lands is the only part of the old act he kept.',
  koalio: 'Slumbra has traveled with more fairground troupes than he can name, a familiar grey-blue stranger wherever the fair sets up next. He competes to prove gentleness can win — he would genuinely rather ease an opponent to the floor inside his Drowsy Aura than strike them, and his record says the floor is patient enough for both.',
  quokkade: 'Tannik is the fair circuit\'s most relentlessly cheerful competitor — a small warm-tan creature who fights for the crowds, the friendships, and the picnic afterwards, in roughly that order. Every arena gets the same Cheer, because every arena, as far as Tannik is concerned, is the same wonderful place.',
  sylvaglide: 'Leafwisp grew up the smallest member of a fair too used to moving fast to wait for stragglers, and learned early to ride draughts nobody else could feel. She has spent her whole career turning being underestimated into an ambush — the Glide Strike arrives from an angle that was empty a moment ago.',
  tazzik: 'Every fair Razzhorn has traveled with learns to read the signs and start packing a little early. The arena is the only place that can absorb the little red demon\'s full appetite — Devour is not a metaphor — and he is fiercely, secretly loyal to anyone who can weather it and grin back.',
  // --- Aquatic: the deep stirs ---
  maelurk: 'Oozehorn was one of the first to feel the old trenches stir, and unlike most of what lives down there, the horned green ooze moved toward the strangeness instead of away from it. He surfaced out of pure curiosity, and treats every Tentacle Barrage as an experiment he is enjoying immensely.',
  nautilux: 'Coralux is a thousand-tide drifter who has weathered every storm, including whatever is moving in the deep dark now. The shell-orange elder competes not to conquer but to endure, taking slow, deep pride in a Ward no storm has ever broken.',
  carcharun: 'Gravemaw surfaced long before anyone spoke of the trenches stirring, and the slab-shouldered slate beast has watched entire leagues rise and crumble since. He returns each season to mentor the young monsters now following him up from the dark, and to remind an impatient Circuit that Weathered Hide beats fresh fury — patience outlasts power.',
  mantaris: 'Veilfin was one of the first in the deep to feel the stirring, and unlike his kin he glided up toward it. A soft-violet showman of the open water, curious and unbothered by a crowd — hooked on the hush right before the Wing Current sweeps a whole line off balance.',
  lanterix: 'Lumigel was born in true darkness, far below where the stirring first began, with nothing but his own soft pink glow for company. He carries that deep light to the surface now, drawn up by the same restlessness moving through the trenches — the Abyssal Glow is a small piece of the abyss that followed him into the ring.',
  // --- Insectoid: decline & new nests ---
  scarabrute: 'Scarabron spent a century as the keystone of a dam his colony built, holding back a river with his own bronze shell. When the colony finished their work and moved on, he found the Circuit — the only place left where something is allowed to hit him as hard as the river did, and where Chitin Plate is still a calling rather than a curiosity.',
  mantevoke: 'Bristleye guarded a temple garden fewer visitors bother to find anymore — a green, thorn-crowned orb holding one unblinking watch, perhaps the last of his line still keeping the old discipline. He competes to test whether that discipline still means anything in a world that has stopped watching. The Ambush says it does.',
  arachnyx: 'Pincerax has never once left her lair to fight — opponents are escorted in past the scarlet armour plate stacked like trophies. Reports of new nests appearing in territories long empty have left the old duellist, for the first time, curious about the wider world instead of dismissive of it.',
  vespera: 'Vesperon is a queen whose hive grew so vast and self-sufficient it no longer needed her orders — exactly the kind of new order the old colonies are quietly giving way to. She entered the Circuit to feel needed again, and Hive Command still carries: ten thousand loyal wings follow the yellow-and-black songwing into every arena anyway.',
  odonatra: 'Duskdart hatched in one of the new nests quietly appearing where the old territories fell empty — young, fast, and utterly unbothered by whatever came before her. The dusk-cyan skimmer flew through a tournament grounds by accident, dodged everything thrown at her on the way out, and came back the next season to do it on purpose.',
  // --- Reptilian: the long wait ends ---
  crocmaw: 'Mirejaw waited motionless in his bog for so long that maps marked the olive ridge of his back as terrain. The Circuit is the first thing in decades that made him move — and when the Death Roll finally turns, the arena floor files the same complaint the bog used to.',
  iguanor: 'Regalor deposed no one and conquered nothing — a retinue simply formed around the gold-and-ivory grandee because he looks magnificent at rest, and then it waited, for years, doing nothing in particular. He competes to finally prove the crown he never asked for was deserved, and the Crest Display suggests he has stopped doubting it himself.',
  serpwyn: 'Sandsaur read the futures of champions for forty seasons before deciding to test whether prophecy is easier from inside the arena. The sand-yellow saurian moves like heat-haze and has never been surprised by an opponent. Not once — ask anyone caught in the Hypnotic Gaze.',
  geckari: 'Emberimp grew up scaling the arena\'s outer walls to watch matches for free, long before he had a way in. The little ember-orange clinger fights the way he watched — from angles nobody thinks to defend, which is what Wall Runner has always really meant.',
  tortavos: 'Mosscap signed up for the Circuit two hundred years ago and arrived last spring, entirely unbothered. Time moves differently under the moss-green dome, and opponents who rush the old king tend to find that out the hard way — Inner Calm is not a state of mind, it is a climate.',
  // --- Draconic: the licensed fire — the Old Flights condescend to attend ---
  pyraxon: 'The Old Flights kept their own courts in the high wastes for centuries and considered the Circuit beneath them — until the crowds grew too large to ignore. Pyrodrake attends as the ember court\'s emissary, banks the arena in heat, and treats every match as a diplomatic incident he intends to win. Draconic Pride is not an innate so much as a condition of his attendance.',
  frostwyren: 'Glacidrake is the glacier court\'s scholar, glazed in blue, older than the licence system that permits her to fight and unimpressed by it. Frost gathers on the rails when she enters. She competes the way she studies: patiently, thoroughly, and with a Blizzard held in reserve for anyone who mistakes patience for hesitation.',
  stormlerath: 'The storm court sent its fastest — a violet drake who arrives a heartbeat before his own thunder and leaves before the echo settles. Voltdrake finds the Circuit\'s rules quaint and its crowds intoxicating, and the Dodge Storm is him showing off to both at once.',
  verdantdrake: 'The green court alone voted against attending, and Verdrake came anyway — the forest\'s answer to a siege, sent to make sure the other flights behave. She fights rooted, Life Bloom mending whatever the match tears, and has quietly become the reason the draconic licence has never been revoked.',
  voidmaw: 'The courts do not speak of a fifth flight, which is exactly the kind of silence Voidfiend enjoys occupying. The blue-black devourer holds a legal licence, files immaculate paperwork, and radiates Entropy — and nobody at the licensing guild can remember who signed the approval.',
  // --- Abyssal: what stirred — the deep given a stage before it takes one ---
  tenebrae: 'When the trenches began to stir, the guilds faced a choice: bar the abyss from the sport, or give it a stage and keep it where the stewards can see it. Duskgeist was the first through the door — a bat-eared shade in deep violet who fights from the Cloak of Shadow and signs autographs afterwards, which unsettles people more than the fighting does.',
  abyssomancer: 'Skulgeist drifts in a shroud of night-purple, a bone-white skull where a face should be, and casts through a Rift the licensing inspectors have politely declined to look inside. The Mana Theft is legal. The guild checked. Twice.',
  lurkerss: 'Morgrel should not still be moving, and moves anyway — a green shambler that walked out of the deepest trench carrying an Ancient Knowing no one taught it. It is patient, endless, and unfailingly courteous, which the Circuit has decided to find charming rather than think about.',
  'chrono-leviathan': 'Chronotide rose from the deep with its tentacles moving a half-second out of time, and the stirring rose with it. The aged-teal titan does not fight so much as arrive at the version of the match where it has already won — Temporal Distortion is the polite word the stewards settled on.',
  cephalumbra: 'Umbratide pools like spilled ink and strikes from its own darkness — a shadow-violet thing the deep sent up, the stewards suspect, as a scout. It Phase Shifts through blows that have already landed, and its match footage is the most rewatched and least understood on the Circuit.',
  // --- Mythical: the ones the stories were about ---
  titanrex: 'The stories said something apex once walked the old world, and the stories undersold it. Titanus is grey-green plate over the patience of extinct ages, holder of an Elite Licence and the Circuit\'s only standing ground-repair invoice. Unstoppable is not marketing.',
  stellarion: 'Stellith watches the way the night sky watches — star-pale, horn-crowned, and precise past the point of comfort. The legends say it came down to see the arenas the stories kept mentioning; the Stellar Shot suggests it intends to be worth the stories written next.',
  wisdomkeeper: 'The mask is older than the league it fights in, and Maskelder has never once removed it. The elder walks the Circuit reading matches three moves before they happen — Foresight as a courtesy, Truth\'s Word as a verdict — and every champion eventually makes the pilgrimage to lose to it on purpose.',
  'archmage-aleph': 'The first of the old order of arena mages, Magivex wrote the duelling forms every caster on the Circuit still unknowingly uses. The green conjurer under the crooked violet hat has outlived the order, the forms, and most of the record books — and the Spell Echo means every casting is also a small history lesson.',
  harmonybringer: 'The stories promised something radiant would come when the sport mattered enough, and Aurelith took that as an invitation. A gold light that trails like a hymn, it fights by making its whole team briefly legendary — Unison is the story, retold with the audience inside it.',
  // --- Saurian: the Lab\'s first cross — warm blood\'s urgency, cold blood\'s patience ---
  grendscale: 'The Lab\'s first stable cross paired mammalian fire with reptilian armour, and Gillbrute is what took: a heavy green bruiser with a sea-cold, gilled stare and a Primal Roar from the warm half of his ancestry. He runs on two calendars at once and has stopped apologising for either.',
  vipramane: 'Venimp got the serpent\'s strike and the mammal\'s restlessness, and no patience from anywhere. The venom-green sprite is small, quick, and deeply unfair — the Mane Bristle is the only warning anyone gets, and it is not much of one.',
  thornhide: 'Mossbrist inherited hide from one line and thorns from the other, and grew both until walking into him became the whole argument. The moss-brown bristle-orb is the Lab\'s proof that a defensive cross compounds: Thornplate over Ironscale, patience over patience.',
  runewyrm: 'Something in the cross woke an older script — sigils flicker along Runeflight\'s wings that neither parent line carries. The rune-violet flier reads them mid-cast the way an heir reads a will: carefully, and with growing interest in the Petrifying Gaze clause.',
  basilroar: 'Embersaur took the bellow from the warm line and the audience from nowhere — a rust-red saurian whose Dread Bellow empties the front rows and whose Rally Cry refills them. The Lab bred a bruiser and got an orator; the Circuit has decided not to correct the mistake.',
  // --- Tempestine: where sky meets sea — weather given a body ---
  thunderoc: 'The Lab crossed the scattering\'s fliers with the stirring\'s swimmers and got weather with opinions. Stormtalon is the storm-gold proof — a terror of the high thermals who dives with the Chain Lightning already committed, the sky\'s verdict delivered before the defence convenes.',
  galewing: 'Galecrest rides gusts of its own making, storm-cyan and never quite where the last gust left it. The Wind Veil is not evasion, strictly — it is the weather agreeing to stand between Galecrest and the consequences.',
  tidecaller: 'Tidegale speaks to currents in a sea-green murmur, and the tide listens — eventually, reluctantly, completely. The Deluge arrives the way weather does: forecast by everyone, prevented by no one.',
  maelstrom: 'Vortiqua is the cross at its most literal — a deep-blue spiral of sky-charge and sea-pull, Overcharge wrapped around an undertow. The water remembers everywhere it has been; the Static Field makes sure the opponents do too.',
  brinehowl: 'Brinefiend carries the cold of the sea floor in a teal-skinned frame and a Gale Cry that tastes of salt at the back row. The deep half mourns, the sky half rallies, and the Rally Squall is both at once — the Circuit\'s only battle-hymn with an undertow.',
  // --- Broodkin: the fair that never leaves — showmanship crossed with the hive ---
  chitinhop: 'The Lab crossed the fair\'s showmanship with the hive\'s numbers, and Jadewing is the opening act: a jade-shelled skipper who bounces between blows on quick glassy wings and Digs In the moment the act needs a finale. The Carapace is real; the delight is realer.',
  broodmother: 'Broodclaw travels with her nest, and her nest travels with the fair — a plum-shelled matriarch whose swarm strikes the tents, raises the ring, and fills the cheap seats. Brood Tend runs the family; Hive Mind runs the match.',
  mantiskin: 'Huskthorn is the fair\'s knife-act gone feral — a burnt-orange husk of dried thorns that folds flat as a poster until the Ambush Fold opens, all Blade Arms and no warning. What it lost in colour it kept in edge.',
  resinback: 'Amberling was the colony\'s mason once, stone joints sealed in the amber of old work. The fair found the golem holding up a collapsed pavilion out of habit and hired it on the spot — Resin Plate for the crowd-surge, Amber Set for the headliner who needs a wall.',
  swarmherd: 'Swarmel is many things agreeing to be one thing, and the fair bills it as exactly that. The green mass performs in the ring and mingles in the stands simultaneously, which the stewards have ruled is one entrant, and the Command Swarm keeps the vote unanimous — most of the time.',
  // --- Primeval: the prestige fusion — first-age titans remade in the Lab ---
  aeonrex: 'When a Mythical frame is fused with dragon-blood, what wakes up remembers the dawn age — and resents having missed the ages since. Magnos, the amber elder giant, treats every arena he enters as territory reclaimed, and Dawn Fury as the paperwork.',
  stellavore: 'The old stories say the gaps between constellations are bite marks. Vorastra — magenta, olive, horns curling like galaxies going wrong — neither confirms nor denies, but opponents report the arena lights dimming when the Light Drinker draws.',
  chronoshell: 'An era is sealed inside Bronzecap\'s aged dome — tamers who press an ear to it swear they hear weather. The crowned elder does not dodge; inside the Era Shell, the moment simply hasn\'t arrived where the blow lands.',
  originmage: 'The first spell ever cast never actually ended — it has just been looking for a caster sturdy enough to keep casting it. The Lab finally built one out of what remains when everything else about a mage burns away: Ossari, bone and craft and nothing else, still working.',
  worldsong: 'The song that shaped the world lost its singer eons ago. Songlume — an ivory radiance in the shape of a spirit, glowing from within — picks up the melody mid-verse with the Genesis Chord, and arenas fall silent to let her finish.',
}
