// 16x16 pixel-art sprites, one silhouette per body type (§8, pixel-art plan).
// Each species is the same silhouette tinted by its own palette, so species read
// as distinct creatures while keeping the art scope small.
// Legend: '.' transparent · X outline · B body · L belly/light · A accent · E eye · P pupil
import { BodyType } from './core'

export const SPRITES: Record<BodyType, string[]> = {
  Mammal: [
    '................',
    '...XX......XX...',
    '..XBBX....XBBX..',
    '..XBBXXXXXXBBX..',
    '.XBBBBBBBBBBBBX.',
    '.XBEPBBBBBBBBBX.',
    '.XBBBBBBBBBBBBX.',
    '.XBBBBBBBBBBBBX.',
    '.XBLLLLLLLLLLBX.',
    '.XBBBBBBBBBBBBX.',
    '.XBBBBBBBBBBBBX.',
    '..XX.XX..XX.XX..',
    '..XX.XX..XX.XX..',
    '..XX.XX..XX.XX..',
    '................',
    '................',
  ],
  Avian: [
    '................',
    '.....XXXX.......',
    '....XBBBBXX.....',
    '...XBBBBBBBX....',
    '..XBBBEPBBBBXA..',
    '..XBBBBBBBBBXAA.',
    '..XBLLBBBBBBXA..',
    '..XBLLLBBBBBX...',
    '...XBBBBBBBBX...',
    '....XBBBBBBX....',
    '.....XXXXXX.....',
    '.....X..X.......',
    '.....X..X.......',
    '....XX..XX......',
    '................',
    '................',
  ],
  Marsupial: [
    '................',
    '....X....X......',
    '...XX....XX.....',
    '...XBXXXXXBX....',
    '..XBBBBBBBBBX...',
    '..XBBEPBBBBBX...',
    '..XBBBBBBBBBX...',
    '...XBBBBBBBX...A',
    '...XBBBBBBBX..AA',
    '..XBLLLLLLBX..AA',
    '..XBLLLLLLBX.AA.',
    '..XBBBBBBBBX.A..',
    '..XBBXXXXBBX....',
    '.XXXX..XXXX.....',
    '.XXX....XXX.....',
    '................',
  ],
  Aquatic: [
    '................',
    '.......XX.......',
    '......XXXX......',
    'A....XBBBBX.....',
    'AA..XBBBBBBX....',
    'AAAXBBBEPBBBX...',
    'AAXBBBBBBBBBBX..',
    'AAXBBLLLLLLBBX..',
    'AAXBBBBBBBBBBX..',
    'AAAXBBBBBBBBX...',
    'AA..XBBBBBBX....',
    'A....XBBBBX.....',
    '......XXXX......',
    '.......XX.......',
    '................',
    '................',
  ],
  Insectoid: [
    '................',
    '..A..........A..',
    '...A........A...',
    '....XXXXXXXX....',
    '...XBBBAABBBX...',
    '..XBBBBAABBBBX..',
    '..XBEPBAABBBBX..',
    '..XBBBBAABBBBX..',
    '..XBLLBAABLLBX..',
    '..XBBBBAABBBBX..',
    '...XBBBAABBBX...',
    '....XXXXXXXX....',
    '..XX..XX..XX....',
    '.XX..XX..XX.....',
    '................',
    '................',
  ],
  Reptilian: [
    '................',
    '................',
    '.....XXXX.......',
    '....XBBBBX..A...',
    '....XBEPBX.AA...',
    '.....XBBBXAA....',
    '....XXBBBBXX....',
    '..XXBBBBBBBBXX..',
    '.XBBBBLLLLBBBBX.',
    '.XBBBBLLLLBBBBXA',
    '.XBBBBBBBBBBBXAA',
    '..XBBXXXXXXBBXA.',
    '..XX........XX..',
    '..XX........XX..',
    '................',
    '................',
  ],
  Draconic: [
    '................',
    '......XXXX......',
    '.....XBBBBX.....',
    '....XBBBBBX.....',
    '...XBBBEPBBX....',
    '..XBBBBBBBBBX...',
    '..XBBABBABBBBX..',
    '.XBBBBBBBBBBBX..',
    '.XBLLBBABBBBX...',
    '.XBBBBBBBBBBX...',
    '..XBBBBBBBBX....',
    '...XXXBBBX......',
    '......XXXX......',
    '......X..X......',
    '................',
    '................',
  ],
  Abyssal: [
    '................',
    '.....XXXXX......',
    '....XBBBBBX.....',
    '...XBBBBBBBBX...',
    '..XBBBEPBBBBX...',
    '..XBBABBBABBX...',
    '..XBBBABBABBX...',
    '..XBBBBBBBBBX...',
    '.XBLLBBBBBBBX...',
    '.XBBBABBABBBBX..',
    '..XBBBBBBBBBX...',
    '...XBBBBBBBX....',
    '....XBBBBBX.....',
    '.....XXXXXX.....',
    '................',
    '................',
  ],
  Mythical: [
    '................',
    '.....XXXXX......',
    '....XBBBBBBX....',
    '...XBBBBBBBBBX..',
    '..XBBBEPBBBBX...',
    '..XBBBABBABBX...',
    '.XBBBBABABBBBX..',
    '.XBLLBBBBBBBBX..',
    '.XBBBBBBBBBBX...',
    '..XBBBBBABBX....',
    '..XBABBABBABBX..',
    '...XBBBBBBBX....',
    '....XBBBBBX.....',
    '.....XXXXX......',
    '................',
    '................',
  ],
  // Fusion classes (v0.7) — structural placeholders until real art is generated.
  Saurian: [
    '................', '................', '.....XXXX.......', '....XBBBBX..A...',
    '....XBEPBX.AA...', '.....XBBBXAA....', '....XXBBBBXX....', '..XXBBBBBBBBXX..',
    '.XBBBBLLLLBBBBX.', '.XBBBBLLLLBBBBXA', '.XBBBBBBBBBBBXAA', '..XBBXXXXXXBBXA.',
    '..XX........XX..', '..XX........XX..', '................', '................',
  ],
  Tempestine: [ // reuses the Avian silhouette
    '................', '.....XXXX.......', '....XBBBBXX.....', '...XBBBBBBBX....',
    '..XBBBEPBBBBXA..', '..XBBBBBBBBBXAA.', '..XBLLBBBBBBXA..', '..XBLLLBBBBBX...',
    '...XBBBBBBBBX...', '....XBBBBBBX....', '.....XXXXXX.....', '.....X..X.......',
    '.....X..X.......', '....XX..XX......', '................', '................',
  ],
  Broodkin: [ // reuses the Insectoid silhouette
    '................', '..A..........A..', '...A........A...', '....XXXXXXXX....',
    '...XBBBAABBBX...', '..XBBBBAABBBBX..', '..XBEPBAABBBBX..', '..XBBBBAABBBBX..',
    '..XBLLBAABLLBX..', '..XBBBBAABBBBX..', '...XBBBAABBBX...', '....XXXXXXXX....',
    '..XX..XX..XX....', '.XX..XX..XX.....', '................', '................',
  ],
  Primeval: [ // v0.88 prestige fusion — structural fallback only; real art ships in speciesArt.ts
    '................', '.......A........', '......AAA.......', '....XXXXXXX.....',
    '...XBBBBBBBX....', '..XBBEPBBBBBX...', '..XBBBBBBBBBX...', '.AXBLLLLLLLBXA..',
    '.AXBLLLLLLLBXA..', '..XBBBBBBBBBX...', '...XBBBBBBBX....', '....XXXXXXX.....',
    '.....XX.XX......', '.....XX.XX......', '................', '................',
  ],
}

export function palette(hue: number): Record<string, string> {
  return {
    X: `hsl(${hue} 45% 22%)`,
    B: `hsl(${hue} 55% 50%)`,
    L: `hsl(${hue} 48% 72%)`,
    A: `hsl(${(hue + 35) % 360} 65% 55%)`,
    E: '#f4f4f8',
    P: '#14161f',
  }
}
